### ISSUE TITLE
[BUG] dbmanager spec is flaky

### ISSUE THREAD

**Issue by duncdrum** [eXist-db/eXide#651]
**Describe the bug**

the spec is flaky because it doesn't reliably deal with the initial notice windows exide offers. So tests will fail because the elements that cypress is trying to interact with aren't visible or focused. 

**Expected behavior**
Robust tests with predictable behaviour

**Screenshots**
<img width="1512" alt="Screenshot 2023-12-19 at 22 27 13" src="https://github.com/eXist-db/eXide/assets/6205362/5b20a2d3-039c-40dd-ac3e-2ad2cf110980">

**Context (please always complete the following information):**
 - eXist-db Version: [6.2.0, 7.0.0-SNAPSHOT]
 - Java Version: [8, 17]
 -  Node Version: [18, 20]
-  App Version: [3.5.1]

**Comment by joewiz** [comment]
Related: #652

**Comment by joewiz** [comment]
Here's something strange that's perhaps related? @line-o's PR #711 passed CI, but the merge commit failed CI: https://github.com/eXist-db/eXide/actions/runs/10540075485. The failing tests involved dbmanager:

```
  19 passing (1m)
  2 failing

  1) DB Manager
       DB Manager operations
         cut operation
           should create collection to be copied:
     AssertionError: Timed out retrying after 4000ms: Expected to find content: 'toBeCopiedAéB' within the selector: 'div[role=gridcell][col-id=name]' but never did.
      at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/integration/dbmanager.spec.js:354:75)

  2) DB Manager
       DB Manager operations
         cut operation
           should cut the collection:
     AssertionError: Timed out retrying after 4000ms: Expected to find content: 'toBeCopiedAéB' within the selector: 'div[role=gridcell][col-id=name]' but never did.
      at Context.eval (http://localhost:8080/__cypress/tests?p=cypress/integration/dbmanager.spec.js:381:14)
```
