### ISSUE TITLE
Popup showing XQuery errors drop < > characters from error description

### ISSUE THREAD

**Issue by vladimirkroupa** [eXist-db/eXide#68]
eXide 2.0.9.
![exide](https://cloud.githubusercontent.com/assets/1022720/3876353/67a90b4a-215b-11e4-8473-3ba4f82c4a9e.png)
I would expect to see `<foo>bar</foo>` as the error description.

**Comment by dizzzz** [comment]
please could you paste the exact query hewer to avoid confusion? Where comes the expectation from?

``` xquery
xquery version "3.0";

error( QName('exist', 'test'), serialize(<foo>bar</foo>) )
```

results with saxon into

```
Engine name: Saxon-EE XQuery 9.5.1.3
Severity: fatal
Description: XPST0003: expected ";", found "<function>("
Start location: 3:0
URL: http://www.w3.org/TR/xpath20/#ERRXPST0003
```

the query is not valid...... which is strange....
- http://www.w3.org/TR/xpath-functions/#func-error
- http://www.w3.org/TR/xpath-functions-30/#func-serialize

**Comment by vladimirkroupa** [comment]
I think there's a semicolon missing after the XQuery declaration.

`xquery version "3.0";`

`error(QName('exist', 'test'), serialize(<foo>bar</foo>))`

**Comment by dizzzz** [comment]
Ah, right; that is the issue of non-copyable-text :-)

running the java client I see

```
org.xmldb.api.base.XMLDBException: test <foo>bar</foo> [at line 3, column 1, source: String]
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:456)
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
    at org.exist.client.QueryDialog$QueryThread.run(QueryDialog.java:612)
Caused by: org.exist.xquery.XPathException: test <foo>bar</foo> [at line 3, column 1, source: String]
    at org.exist.xquery.functions.fn.FunError.eval(FunError.java:139)
    at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70)
    at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
    at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
    at org.exist.xquery.XQuery.execute(XQuery.java:297)
    at org.exist.xquery.XQuery.execute(XQuery.java:217)
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
    ... 2 more
Caused by: org.exist.xquery.XPathException: test <foo>bar</foo> [at line 3, column 1, source: String]
    at org.exist.xquery.functions.fn.FunError.eval(FunError.java:139)
    at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70)
    at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
    at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
    at org.exist.xquery.XQuery.execute(XQuery.java:297)
    at org.exist.xquery.XQuery.execute(XQuery.java:217)
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
    at org.exist.client.QueryDialog$QueryThread.run(QueryDialog.java:612)

```

where as 

``` xquery
error(QName('exist', 'test'), "aaa")
```

results into an equivalent trace:

```
org.xmldb.api.base.XMLDBException: test aaa [at line 3, column 1, source: String]
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:456)
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
    at org.exist.client.QueryDialog$QueryThread.run(QueryDialog.java:612)
Caused by: org.exist.xquery.XPathException: test aaa [at line 3, column 1, source: String]
    at org.exist.xquery.functions.fn.FunError.eval(FunError.java:139)
    at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70)
    at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
    at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
    at org.exist.xquery.XQuery.execute(XQuery.java:297)
    at org.exist.xquery.XQuery.execute(XQuery.java:217)
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
    ... 2 more
Caused by: org.exist.xquery.XPathException: test aaa [at line 3, column 1, source: String]
    at org.exist.xquery.functions.fn.FunError.eval(FunError.java:139)
    at org.exist.xquery.BasicFunction.eval(BasicFunction.java:70)
    at org.exist.xquery.InternalFunctionCall.eval(InternalFunctionCall.java:56)
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
    at org.exist.xquery.PathExpr.eval(PathExpr.java:264)
    at org.exist.xquery.AbstractExpression.eval(AbstractExpression.java:71)
    at org.exist.xquery.XQuery.execute(XQuery.java:297)
    at org.exist.xquery.XQuery.execute(XQuery.java:217)
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:452)
    at org.exist.xmldb.LocalXPathQueryService.execute(LocalXPathQueryService.java:157)
    at org.exist.client.QueryDialog$QueryThread.run(QueryDialog.java:612)

```

so your analysis is right, eXide should probably make the elements visible as described

**Comment by dizzzz** [comment]
In your own app you do have access to the info:

``` xquery
xquery version "3.0";

try {
  error( QName('exist', 'test'), serialize(<foo>bar</foo>) )
} catch * {
    <error>Caught error {$err:code}: {$err:description}. Data: {$err:value}</error>
}
```
